name = "catarina-estetica"
compatibility_date = "2026-07-03"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "SITE_CONFIG"
id = "f619b37b517342fcae5d7e654e6c913a"
preview_id = "f619b37b517342fcae5d7e654e6c913a"
