function json(x,s=200){return new Response(JSON.stringify(x,null,2),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function fallback(request){try{let r=await fetch(new URL('/config/site.v2.json',request.url));if(r.ok)return await r.json()}catch{}return {version:2,site:{name:'Catarina Queiroz'},theme:{colors:{},layout:{}},sections:{}}}
function admin(request,env){let cookie=request.headers.get('cookie')||'';if(cookie.includes('cq_session=ok'))return true;let token=encodeURIComponent(env.ADMIN_SESSION_SECRET||env.ADMIN_PASSWORD||'');return !!token&&cookie.includes('cq_session='+token)}
function clone(x){return JSON.parse(JSON.stringify(x||{}))}
function appendDefaults(config,base,path,min){let parts=path.split('.');let a=config,b=base;for(let p of parts){a=a&&a[p];b=b&&b[p]}if(!Array.isArray(a)||!Array.isArray(b))return;let seen=new Set(a.map(x=>String((x&&x.title)||(x&&x.name)||(x&&x.question)||(x&&x.text)||x)));for(let item of b){if(a.length>=min)break;let key=String((item&&item.title)||(item&&item.name)||(item&&item.question)||(item&&item.text)||item);if(!seen.has(key)){a.push(clone(item));seen.add(key)}}}
function normalize(config,base){config=config||{};config.sections=config.sections||{};base=base||{};appendDefaults(config,base,'sections.procedures.items',8);appendDefaults(config,base,'sections.testimonials.items',8);if(!config.sections.ticker)config.sections.ticker={};if(!Array.isArray(config.sections.ticker.items)){let items=(config.sections.procedures&&config.sections.procedures.items||[]).map(x=>({text:x.title,visible:true})).filter(x=>x.text);config.sections.ticker.items=items}return config}
function cleanPublic(config){let c=JSON.parse(JSON.stringify(config||{}));if(c.pixels){delete c.pixels.serverAccessToken;delete c.pixels.conversionsApiToken;delete c.pixels.serverToken}return c}
export async function onRequestGet({request,env}){let base=await fallback(request);let config=clone(base);if(env.SITE_CONFIG){let saved=await env.SITE_CONFIG.get('site-config-v2','json');if(saved)config=saved}config=normalize(config,base);return json({config:admin(request,env)?config:cleanPublic(config)})}
export async function onRequestPut({request,env}){if(!admin(request,env))return json({error:'Não autorizado. Faça login no /adm antes de salvar.'},401);if(!env.SITE_CONFIG)return json({error:'Configure SITE_CONFIG no Cloudflare'},500);let base=await fallback(request);let body=await request.json();let config=normalize(body.config||body,base);config.version=2;await env.SITE_CONFIG.put('site-config-v2',JSON.stringify(config));return json({ok:true,config})}
export const onRequestPost=onRequestPut;
