function json(x,s=200){return new Response(JSON.stringify(x,null,2),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
async function fallback(request){try{let r=await fetch(new URL('/config/site.v2.json',request.url));if(r.ok)return await r.json()}catch{}return {version:2,site:{name:'Catarina Queiroz'},theme:{colors:{},layout:{}},sections:{}}}
const HARD_PROCEDURES=[
{title:'Limpeza de Pele',category:'FACIAL',description:'Remove impurezas, cravos, células mortas e excesso de oleosidade, promovendo pele mais limpa, saudável e renovada.',imageUrl:'',imageLabel:'LIMPEZA DE PELE',imageNote:'substitua por foto real do procedimento',tags:['Pele renovada','Hidratação'],visible:true},
{title:'Drenagem Facial',category:'FACIAL',description:'Massagem suave que estimula circulação e sistema linfático, reduzindo inchaço, melhorando contorno facial e aparência descansada.',imageUrl:'',imageLabel:'DRENAGEM FACIAL',imageNote:'substitua por foto real do procedimento',tags:['Leveza','Contorno'],visible:true},
{title:'Peeling Químico',category:'FACIAL',description:'Utiliza ativos específicos para renovação da pele, suavização de manchas, textura irregular, marcas de acne, linhas finas e opacidade.',imageUrl:'',imageLabel:'PEELING QUÍMICO',imageNote:'substitua por foto real do procedimento',tags:['Luminosidade','Textura'],visible:true},
{title:'Drenagem HD',category:'CORPORAL',description:'Protocolo corporal para sensação de leveza, retenção de líquidos e definição visual, sempre após avaliação individual.',imageUrl:'',imageLabel:'DRENAGEM HD',imageNote:'substitua por foto real do procedimento',tags:['Corpo','Leveza'],visible:true},
{title:'Botox',category:'FACIAL',description:'Aplicação planejada para suavizar sinais, preservando expressão e naturalidade.',imageUrl:'',imageLabel:'BOTOX',imageNote:'substitua por foto real do procedimento',tags:['Naturalidade'],visible:true},
{title:'Endolaser',category:'TECNOLOGIA',description:'Tecnologia para protocolos corporais e faciais, sempre com avaliação e indicação adequadas.',imageUrl:'',imageLabel:'ENDOLASER',imageNote:'substitua por foto real do procedimento',tags:['Tecnologia'],visible:true},
{title:'Lipo Enzimática',category:'CORPORAL',description:'Protocolo estético corporal definido conforme avaliação, objetivo e segurança.',imageUrl:'',imageLabel:'LIPO ENZIMÁTICA',imageNote:'substitua por foto real do procedimento',tags:['Corpo','Definição'],visible:true},
{title:'Protocolos Corporais',category:'CORPORAL',description:'Combinações personalizadas para bem-estar, contorno e autoestima.',imageUrl:'',imageLabel:'PROTOCOLOS CORPORAIS',imageNote:'substitua por foto real do procedimento',tags:['Personalizado'],visible:true}
];
const HARD_TESTIMONIALS=[1,2,3,4,5,6,7,8].map(n=>({name:'Cliente '+String(n).padStart(2,'0'),role:n%2?'Atendimento facial':'Protocolo corporal',text:['Atendimento muito cuidadoso, com explicação clara do protocolo e um ambiente lindo.','Me senti acolhida desde o primeiro contato. Tudo foi explicado com muita calma.','Amei a experiência. A pele ficou com sensação de limpeza e leveza.','Gostei muito da avaliação individual e do cuidado no acompanhamento.','Ambiente confortável e atendimento muito organizado.','A orientação antes do procedimento me deixou muito segura.','Resultado natural e experiência muito boa.','Voltaria e indicaria para outras pessoas.'][n-1],imageUrl:'',beforeImageUrl:'',afterImageUrl:'',visible:true}));
function admin(request,env){let cookie=request.headers.get('cookie')||'';if(cookie.includes('cq_session=ok'))return true;let token=encodeURIComponent(env.ADMIN_SESSION_SECRET||env.ADMIN_PASSWORD||'');return !!token&&cookie.includes('cq_session='+token)}
function clone(x){return JSON.parse(JSON.stringify(x||{}))}
function getPath(obj,path){return path.split('.').reduce((a,p)=>a&&a[p],obj)}
function setPath(obj,path,value){let parts=path.split('.'),ref=obj;while(parts.length>1){let p=parts.shift();ref[p]=ref[p]||{};ref=ref[p]}ref[parts[0]]=value}
function appendList(config,base,path,min,hard){let a=getPath(config,path);if(!Array.isArray(a)){setPath(config,path,[]);a=getPath(config,path)}let b=[...(Array.isArray(getPath(base,path))?getPath(base,path):[]),...(hard||[])];let seen=new Set(a.map(x=>String((x&&x.title)||(x&&x.name)||(x&&x.question)||(x&&x.text)||x).toLowerCase()));for(let item of b){if(a.length>=min)break;let key=String((item&&item.title)||(item&&item.name)||(item&&item.question)||(item&&item.text)||item).toLowerCase();if(!seen.has(key)){a.push(clone(item));seen.add(key)}}}
function normalize(config,base){config=config||{};config.sections=config.sections||{};base=base||{};appendList(config,base,'sections.procedures.items',8,HARD_PROCEDURES);appendList(config,base,'sections.testimonials.items',8,HARD_TESTIMONIALS);if(!config.sections.ticker)config.sections.ticker={};if(!Array.isArray(config.sections.ticker.items)||!config.sections.ticker.items.length){config.sections.ticker.items=(config.sections.procedures.items||[]).map(x=>({text:x.title,visible:true})).filter(x=>x.text)}return config}
function cleanPublic(config){let c=JSON.parse(JSON.stringify(config||{}));if(c.pixels){delete c.pixels.serverAccessToken;delete c.pixels.conversionsApiToken;delete c.pixels.serverToken}return c}
export async function onRequestGet({request,env}){let base=await fallback(request);let config=clone(base);if(env.SITE_CONFIG){let saved=await env.SITE_CONFIG.get('site-config-v2','json');if(saved)config=saved}config=normalize(config,base);return json({config:admin(request,env)?config:cleanPublic(config)})}
export async function onRequestPut({request,env}){if(!admin(request,env))return json({error:'Não autorizado. Faça login no /adm antes de salvar.'},401);if(!env.SITE_CONFIG)return json({error:'Configure SITE_CONFIG no Cloudflare'},500);let base=await fallback(request);let body=await request.json();let config=normalize(body.config||body,base);config.version=2;await env.SITE_CONFIG.put('site-config-v2',JSON.stringify(config));return json({ok:true,config})}
export const onRequestPost=onRequestPut;
