const app=document.querySelector('#app');let cfg;const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
async function load(){for(const u of ['/api/config','/config/site.config.json'])try{const r=await fetch(u,{cache:'no-store'});if(r.ok){const j=await r.json();return j.config||j}}catch{}throw Error('Não foi possível carregar a configuração.')}function setMeta(n,c){let e=document.querySelector(`meta[name="${n}"]`);if(!e){e=document.createElement('meta');e.name=n;document.head.appendChild(e)}e.content=c||''}function setProp(n,c){let e=document.querySelector(`meta[property="${n}"]`);if(!e){e=document.createElement('meta');e.setAttribute('property',n);document.head.appendChild(e)}e.content=c||''}
function wa(){const n=cfg.site.contact.whatsappNumber||'';const m=encodeURIComponent(cfg.site.contact.whatsappMessage||'Olá! Vim pelo site.');return`https://wa.me/${n.replace(/\D/g,'')}?text=${m}`}function href(x){return x==='whatsapp'?wa():x}function img(i){return i?.url?`<img src="${esc(i.url)}" alt="${esc(i.alt||'')}" loading="lazy">`:''}
function theme(){const c=cfg.theme.colors||{},l=cfg.theme.layout||{},r=document.documentElement;Object.entries({navy:'--navy',navyDeep:'--navyDeep',navyBlack:'--navyBlack',cream:'--cream',champagne:'--champagne',rose:'--rose',roseDark:'--roseDark',gold:'--gold',goldLight:'--goldLight',ink:'--ink',muted:'--muted'}).forEach(([k,v])=>c[k]&&r.style.setProperty(v,c[k]));if(l.container)r.style.setProperty('--container',l.container+'px');if(l.sectionPadding)r.style.setProperty('--section',l.sectionPadding+'px');if(l.cardRadius)r.style.setProperty('--radius',l.cardRadius+'px');if(l.cardSpacing)r.style.setProperty('--gap',l.cardSpacing+'px');if(l.titleScale)r.style.setProperty('--titleScale',l.titleScale);if(l.bodyScale)r.style.setProperty('--bodyScale',l.bodyScale);if(cfg.site.logo?.width)r.style.setProperty('--logoWidth',cfg.site.logo.width+'px')}
function pixels(){const p=cfg.site.pixels||{};if(!p.enableTracking)return;if(p.metaPixelId){let s=document.createElement('script');s.innerHTML=`!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');fbq('init','${p.metaPixelId}');fbq('track','PageView');`;document.head.appendChild(s)}const g=p.googleAdsId||p.googleAnalyticsId;if(g){let a=document.createElement('script');a.async=1;a.src=`https://www.googletagmanager.com/gtag/js?id=${encodeURIComponent(g)}`;document.head.appendChild(a);let s=document.createElement('script');s.innerHTML=`window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','${g}');`;document.head.appendChild(s)}}
function brand(){const l=cfg.site.logo||{};return l.imageUrl?`<a class="brand" href="#inicio"><img src="${esc(l.imageUrl)}" alt="${esc(cfg.site.name)}"></a>`:`<a class="brand" href="#inicio"><div><div class="brand-word">${esc(l.text||cfg.site.name)}</div><div class="brand-sub">${esc(l.subtitle||'')}</div></div></a>`}
function nav(){return`<header class="nav"><div class="container nav-inner">${brand()}<nav class="links" id="links">${(cfg.navigation||[]).map(n=>`<a href="${esc(n.href)}">${esc(n.label)}</a>`).join('')}</nav><button class="menu" id="menu" aria-label="menu"><span></span><span></span><span></span></button></div></header>`}
function hero(){const h=cfg.hero;return`<section class="hero" id="inicio"><div class="container hero-grid"><div><div class="eyebrow">${esc(h.eyebrow)}</div><h1>${esc(h.title)}</h1><p>${esc(h.subtitle)}</p><div class="actions"><a class="btn btn-primary" href="${esc(href(h.primaryCta?.href||'whatsapp'))}">${esc(h.primaryCta?.label||'Agendar')}</a><a class="btn btn-outline" href="${esc(href(h.secondaryCta?.href||'#servicos'))}">${esc(h.secondaryCta?.label||'Conhecer')}</a></div><div class="badges">${(h.badges||[]).map(b=>`<span>${esc(b)}</span>`).join('')}</div></div><div><div class="hero-img" style="--pos:${esc(h.image?.position||'center')};--scale:${Number(h.image?.scale||1)}">${img(h.image)}</div><div class="stats">${(h.stats||[]).map(s=>`<div class="stat"><strong>${esc(s.value)}</strong><span>${esc(s.label)}</span></div>`).join('')}</div></div></div></section>`}
function about(){const a=cfg.about;return`<section class="section luxury" id="sobre"><div class="container about-grid"><div class="photo" style="--pos:${esc(a.image?.position||'center')};--scale:${Number(a.image?.scale||1)}">${img(a.image)}</div><div><div class="eyebrow">${esc(a.eyebrow)}</div><h2 class="title">${esc(a.title)}</h2><p class="subtitle">${esc(a.text)}</p><div class="highlights">${(a.highlights||[]).map(x=>`<div class="highlight">${esc(x)}</div>`).join('')}</div></div></div></section>`}
const sym={sparkles:'✦',waves:'≈',leaf:'☘',gem:'◆',heart:'♡',star:'★'};
function services(){const s=cfg.services,it=[...(s.items||[])].sort((a,b)=>(a.order||0)-(b.order||0));return`<section class="section" id="servicos"><div class="container"><div class="center"><div class="eyebrow">${esc(s.eyebrow)}</div><h2 class="title">${esc(s.title)}</h2><p class="subtitle">${esc(s.subtitle)}</p></div><div class="services" style="margin-top:44px">${it.map(x=>`<article class="card">${x.imageUrl?`<div class="service-img"><img src="${esc(x.imageUrl)}" alt="${esc(x.title)}" style="object-position:${esc(x.imagePosition||'center')}"></div>`:`<div class="icon">${sym[x.icon]||'✦'}</div>`}<h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><a class="mini" href="${wa()}">${esc(x.ctaLabel||'Agendar')}</a></article>`).join('')}</div></div></section>`}
function results(){const r=cfg.results;return`<section class="section dark" id="resultados"><div class="container"><div class="eyebrow">${esc(r.eyebrow)}</div><h2 class="title">${esc(r.title)}</h2><p class="subtitle">${esc(r.subtitle)}</p><div class="results">${(r.items||[]).map(i=>`<article class="result"><h3>${esc(i.title)}</h3><p>${esc(i.text)}</p></article>`).join('')}</div></div></section>`}
function testimonials(){const t=cfg.testimonials,it=[...(t.items||[])].filter(x=>x.visible!==false).sort((a,b)=>(a.order||0)-(b.order||0));return`<section class="section luxury" id="depoimentos"><div class="container"><div class="center"><div class="eyebrow">${esc(t.eyebrow)}</div><h2 class="title">${esc(t.title)}</h2><p class="subtitle">${esc(t.subtitle)}</p></div><div class="testimonials" style="margin-top:44px">${it.map(x=>`<article class="card"><div class="stars">${'★'.repeat(Number(x.rating||5))}</div><p>“${esc(x.text)}”</p><div class="client"><div class="avatar">${x.imageUrl?`<img src="${esc(x.imageUrl)}" alt="${esc(x.name)}">`:esc((x.name||'C').slice(0,1))}</div><div><strong>${esc(x.name)}</strong><br><span>${esc(x.role||'')}</span></div></div></article>`).join('')}</div></div></section>`}
function faq(){const f=cfg.faq;return`<section class="section" id="faq"><div class="container"><div class="center"><div class="eyebrow">${esc(f.eyebrow)}</div><h2 class="title">${esc(f.title)}</h2></div><div class="faq" style="margin-top:44px">${(f.items||[]).map((x,i)=>`<div class="faq-item ${i===0?'open':''}"><button class="faq-q"><span>${esc(x.question)}</span><b>+</b></button><div class="faq-a">${esc(x.answer)}</div></div>`).join('')}</div></div></section>`}
function contact(){const c=cfg.site.contact;return`<section class="section contact" id="contato"><div class="container contact-grid"><div><div class="eyebrow">Contato</div><h2 class="title">Agende sua avaliação</h2><p class="subtitle">Fale com a equipe pelo WhatsApp e escolha o melhor horário.</p><div class="actions"><a class="btn btn-primary" href="${wa()}">${esc(c.phoneLabel||'WhatsApp')}</a>${c.instagramUrl?`<a class="btn btn-outline" href="${esc(c.instagramUrl)}" target="_blank">Instagram</a>`:''}</div><p class="subtitle">${esc(c.address||'')}</p></div><div>${c.mapsEmbedUrl?`<div class="map"><iframe src="${esc(c.mapsEmbedUrl)}" loading="lazy"></iframe></div>`:`<div class="empty">Mapa ainda não configurado.</div>`}</div></div></section>`}
function foot(){return`<footer class="footer"><div class="container"><span>© ${new Date().getFullYear()} ${esc(cfg.site.businessName||cfg.site.name)}</span><a href="/adm/">Painel administrativo</a></div></footer><a class="wa" href="${wa()}" aria-label="WhatsApp">☏</a>`}
function render(){app.innerHTML=[nav(),hero(),about(),services(),results(),testimonials(),faq(),contact(),foot()].join('');document.querySelector('#menu')?.addEventListener('click',()=>document.querySelector('#links')?.classList.toggle('open'));document.querySelectorAll('.faq-q').forEach(b=>b.onclick=()=>b.closest('.faq-item').classList.toggle('open'))}
(async()=>{try{cfg=await load();document.documentElement.lang=cfg.site.language||'pt-BR';document.title=cfg.site.seo?.title||cfg.site.name;setMeta('description',cfg.site.seo?.description);setProp('og:title',cfg.site.seo?.title);setProp('og:description',cfg.site.seo?.description);if(cfg.site.seo?.ogImage)setProp('og:image',cfg.site.seo.ogImage);theme();pixels();render()}catch(e){app.innerHTML=`<main class="section"><div class="container"><h1>Erro</h1><p>${esc(e.message)}</p></div></main>`}})();

