const app=document.querySelector('#app');let C;const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function load(){for(const u of ['/api/config','/config/site.v2.json'])try{let r=await fetch(u,{cache:'no-store'});if(r.ok){let j=await r.json();return j.config||j}}catch{}throw Error('Configuração não encontrada')}
function meta(n,c,p=false){let q=p?`meta[property="${n}"]`:`meta[name="${n}"]`;let e=document.querySelector(q)||document.head.appendChild(document.createElement('meta'));p?e.setAttribute('property',n):e.setAttribute('name',n);e.content=c||''}
function theme(){let r=document.documentElement,t=C.theme||{},c=t.colors||{},l=t.layout||{};Object.entries({navy:'--navy',deep:'--deep',ink:'--ink',cream:'--cream',champagne:'--champagne',rose:'--rose',roseDark:'--roseDark',gold:'--gold',goldLight:'--goldLight',soft:'--soft'}).forEach(([k,v])=>c[k]&&r.style.setProperty(v,c[k]));if(l.container)r.style.setProperty('--container',l.container+'px');if(l.radius)r.style.setProperty('--radius',l.radius+'px');if(l.titleScale)r.style.setProperty('--titleScale',l.titleScale);if(l.bodyScale)r.style.setProperty('--bodyScale',l.bodyScale);if(C.site.logo?.width)r.style.setProperty('--logoWidth',C.site.logo.width+'px')}
function wa(){let n=(C.site.contact.whatsappNumber||'').replace(/\D/g,''),m=encodeURIComponent(C.site.contact.whatsappMessage||'Olá!');return `https://wa.me/${n}?text=${m}`}function icon(n){return `<i data-lucide="${esc(n||'sparkles')}"></i>`}
function img(o,cls=''){if(o?.url)return `<div class="${cls} image-frame has-img" style="--pos:${esc(o.position||'center')}"><img src="${esc(o.url)}" alt="${esc(o.alt||'')}" loading="lazy"></div>`;return `<div class="${cls} image-frame"><div class="placeholder">${icon('image')}<span>Imagem editável pelo painel</span></div></div>`}
function brand(){let l=C.site.logo||{};return `<a class="brand" href="#inicio">${l.imageUrl?`<img src="${esc(l.imageUrl)}" alt="${esc(C.site.name)}">`:`<div><div class="brand-main">${esc(l.text||C.site.name)}</div><div class="brand-sub">${esc(l.subtitle||'')}</div></div>`}</a>`}
function nav(){return `<header class="nav"><div class="container nav-inner">${brand()}<nav class="links" id="links">${(C.navigation||[]).map(x=>`<a href="${esc(x.href)}">${icon(x.icon)}${esc(x.label)}</a>`).join('')}</nav><button class="menu" id="menu" aria-label="menu"><span></span><span></span><span></span></button></div></header>`}
function box(i){return `<div class="icon-box">${icon(i)}</div>`}
function hero(){let h=C.sections.hero;let title=esc(h.title).replace(esc(h.highlight),`<em>${esc(h.highlight)}</em>`);return `<section class="section hero bg-dark" id="inicio"><div class="container hero-grid reveal"><div><div class="eyebrow">${esc(h.kicker)}</div><h1>${title}</h1><p>${esc(h.subtitle)}</p><div class="actions"><a class="btn btn-primary" href="${wa()}"><img src="/assets/icons/whatsapp.svg" alt="" width="20">${esc(h.primaryButton)}</a><a class="btn btn-ghost" href="#procedimentos">${esc(h.secondaryButton)}</a></div><p class="text">${esc(h.note)}</p></div><div><div class="hero-card">${img(h.image,'hero-photo')}</div><div class="metric-row">${(h.metrics||[]).map(m=>`<div class="metric"><b>${esc(m.value)}</b><span>${esc(m.label)}</span></div>`).join('')}</div></div></div></section>`}
function trust(){let s=C.sections.trust;return `<section class="section bg-soft" id="confianca"><div class="container reveal"><div class="grid-3">${(s.items||[]).map(x=>`<article class="card">${box(x.icon)}<h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></article>`).join('')}</div></div></section>`}
function complaints(){let s=C.sections.complaints;return `<section class="section bg-cream" id="queixas"><div class="container reveal"><div class="eyebrow">${esc(s.kicker)}</div><h2 class="title">${esc(s.title)}</h2><p class="text">${esc(s.subtitle)}</p><div class="grid-4">${(s.items||[]).map(x=>`<article class="card">${box(x.icon)}<h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></article>`).join('')}</div></div></section>`}
function procedures(){let s=C.sections.procedures;return `<section class="section bg-soft" id="procedimentos"><div class="container reveal"><div class="eyebrow">${esc(s.kicker)}</div><h2 class="title">${esc(s.title)}</h2><p class="text">${esc(s.subtitle)}</p><div class="carousel"><div class="track" id="procTrack">${(s.items||[]).map(x=>`<article class="card slide"><div class="procedure-img">${x.imageUrl?`<img src="${esc(x.imageUrl)}" alt="${esc(x.title)}">`:icon(x.icon)}</div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><a class="btn btn-primary" href="${wa()}" style="margin-top:20px"><img src="/assets/icons/whatsapp.svg" alt="" width="18">Agendar</a></article>`).join('')}</div><div class="carousel-controls"><button class="icon-btn" data-scroll="procTrack:-1">${icon('chevron-left')}</button><button class="icon-btn" data-scroll="procTrack:1">${icon('chevron-right')}</button></div></div></div></section>`}
function method(){let s=C.sections.method;return `<section class="section bg-dark" id="metodo"><div class="container reveal"><div class="eyebrow">${esc(s.kicker)}</div><h2 class="title">${esc(s.title)}</h2><p class="text">${esc(s.subtitle)}</p><div class="steps">${(s.steps||[]).map(x=>`<article class="card step">${box(x.icon)}<h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></article>`).join('')}</div></div></section>`}
function about(){let s=C.sections.about;return `<section class="section bg-soft" id="sobre"><div class="container split reveal"><div>${img(s.image,'about-photo')}</div><div><div class="eyebrow">${esc(s.kicker)}</div><h2 class="title">${esc(s.title)}</h2><p class="text">${esc(s.text)}</p><div class="bullets">${(s.bullets||[]).map(b=>`<div class="bullet">${esc(b)}</div>`).join('')}</div></div></div></section>`}
function authority(){let s=C.sections.authority;return `<section class="section bg-dark" id="autoridade"><div class="container reveal"><div class="eyebrow">${esc(s.kicker)}</div><h2 class="title">${esc(s.title)}</h2><p class="quote">“${esc(s.quote)}”</p><div class="grid-3">${(s.items||[]).map(x=>`<article class="card">${box(x.icon)}<h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></article>`).join('')}</div></div></section>`}
function testimonials(){let s=C.sections.testimonials,items=(s.items||[]).filter(x=>x.visible!==false);return `<section class="section bg-soft" id="depoimentos"><div class="container reveal"><div class="eyebrow">${esc(s.kicker)}</div><h2 class="title">${esc(s.title)}</h2><p class="text">${esc(s.subtitle)}</p><div class="carousel"><div class="track" id="depTrack">${items.map(x=>`<article class="card slide testimonial-card"><div class="stars">${'★'.repeat(Number(x.rating||5))}</div><p>“${esc(x.text)}”</p><div class="client"><div class="avatar">${x.imageUrl?`<img src="${esc(x.imageUrl)}" alt="${esc(x.name)}">`:esc((x.name||'C').slice(0,1))}</div><div><b>${esc(x.name)}</b><br><span>${esc(x.role||'')}</span></div></div></article>`).join('')}</div><div class="carousel-controls"><button class="icon-btn" data-scroll="depTrack:-1">${icon('chevron-left')}</button><button class="icon-btn" data-scroll="depTrack:1">${icon('chevron-right')}</button></div></div></div></section>`}
function faq(){let s=C.sections.faq;return `<section class="section bg-cream" id="faq"><div class="container reveal"><div class="eyebrow">${esc(s.kicker)}</div><h2 class="title">${esc(s.title)}</h2><div class="faq-list">${(s.items||[]).map((x,i)=>`<div class="faq-item ${i===0?'open':''}"><button class="faq-q"><span>${esc(x.question)}</span>${icon('plus')}</button><div class="faq-a">${esc(x.answer)}</div></div>`).join('')}</div></div></section>`}
function location(){let s=C.sections.location,c=C.site.contact;let map=c.mapsEmbedUrl?`<iframe src="${esc(c.mapsEmbedUrl)}" loading="lazy"></iframe>`:`<div class="placeholder">${icon('map-pin')}<span>${esc(c.address||c.mapsQuery||'Endereço a configurar')}</span></div>`;return `<section class="section bg-dark" id="contato"><div class="container split reveal"><div><div class="eyebrow">${esc(s.kicker)}</div><h2 class="title">${esc(s.title)}</h2><p class="text">${esc(s.subtitle)}</p><p class="text">${esc(c.address)}</p><div class="actions"><a class="btn btn-primary" href="${wa()}"><img src="/assets/icons/whatsapp.svg" alt="" width="20">Agendar no WhatsApp</a></div></div><div class="location-box">${map}</div></div></section>`}
function finalCta(){let s=C.sections.finalCta;return `<section class="section bg-soft" id="agendar"><div class="container center reveal"><h2 class="title">${esc(s.title)}</h2><p class="text" style="margin-inline:auto">${esc(s.subtitle)}</p><div class="actions" style="justify-content:center"><a class="btn btn-primary" href="${wa()}"><img src="/assets/icons/whatsapp.svg" alt="" width="20">${esc(s.button)}</a></div></div></section>`}
function footer(){return `<footer class="footer"><div class="container"><span>© ${new Date().getFullYear()} ${esc(C.site.businessName)}</span><a href="/adm/">Painel administrativo</a></div></footer><a class="whatsapp-float" href="${wa()}" aria-label="WhatsApp"><img src="/assets/icons/whatsapp.svg" alt=""></a><a class="mobile-wa" href="${wa()}"><img src="/assets/icons/whatsapp.svg" alt="">Agendar avaliação</a>`}
function dots(){let ids=['inicio','queixas','procedimentos','metodo','depoimentos','contato','agendar'];return `<div class="dots">${ids.map(id=>`<button class="dot" data-go="${id}" aria-label="${id}"></button>`).join('')}</div>`}
function pixels(){let p=C.site.pixels||{};if(!p.enableTracking)return;let g=p.googleAdsId||p.googleAnalyticsId;if(g){let a=document.createElement('script');a.async=1;a.src=`https://www.googletagmanager.com/gtag/js?id=${encodeURIComponent(g)}`;document.head.appendChild(a);let s=document.createElement('script');s.textContent=`window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','${g}');`;document.head.appendChild(s)}if(p.metaPixelId){let s=document.createElement('script');s.textContent=`!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');fbq('init','${p.metaPixelId}');fbq('track','PageView');`;document.head.appendChild(s)}}
function render(){let s=C.sections;app.innerHTML=`${nav()}<main class="snap-shell" id="shell">${s.hero.enabled?hero():''}${s.trust.enabled?trust():''}${s.complaints.enabled?complaints():''}${s.procedures.enabled?procedures():''}${s.method.enabled?method():''}${s.about.enabled?about():''}${s.authority.enabled?authority():''}${s.testimonials.enabled?testimonials():''}${s.faq.enabled?faq():''}${s.location.enabled?location():''}${s.finalCta.enabled?finalCta():''}${footer()}</main>${dots()}`;window.lucide?.createIcons();bind()}
function bind(){document.querySelector('#menu')?.addEventListener('click',()=>document.querySelector('#links')?.classList.toggle('open'));document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>{let [id,dir]=b.dataset.scroll.split(':'),el=document.getElementById(id);el?.scrollBy({left:Number(dir)*380,behavior:'smooth'})});document.querySelectorAll('.faq-q').forEach(b=>b.onclick=()=>b.closest('.faq-item').classList.toggle('open'));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.go)?.scrollIntoView({behavior:'smooth'}));let io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.24});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));let sec=[...document.querySelectorAll('.section[id]')],dots=[...document.querySelectorAll('.dot')];let io2=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){dots.forEach(d=>d.classList.toggle('active',d.dataset.go===e.target.id))}}),{root:document.querySelector('#shell'),threshold:.55});sec.forEach(e=>io2.observe(e))}
(async()=>{try{C=await load();document.documentElement.lang=C.site.language||'pt-BR';document.title=C.site.seo?.title||C.site.businessName;meta('description',C.site.seo?.description);meta('keywords',C.site.seo?.keywords);meta('og:title',C.site.seo?.title,true);meta('og:description',C.site.seo?.description,true);if(C.site.seo?.ogImage)meta('og:image',C.site.seo.ogImage,true);theme();pixels();render()}catch(e){app.innerHTML=`<main class="section"><div class="container"><h1>Erro</h1><p>${esc(e.message)}</p></div></main>`}})();
