const app=document.querySelector('#app');
const W='/assets/icons/whatsapp.svg';
const E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function load(){for(const u of ['/api/config-v2','/config/site.v2.json'])try{const r=await fetch(u,{cache:'no-store'});if(r.ok){const j=await r.json();return j.config||j}}catch{}throw Error('Configuração não encontrada')}
function ico(n){return `<i data-lucide="${E(n||'sparkles')}"></i>`}
function wa(C,t=''){const n=(C.site.contact.whatsappNumber||'').replace(/\D/g,'');const m=encodeURIComponent(t||C.site.contact.whatsappMessage||'Olá!');return `https://wa.me/${n}?text=${m}`}
function brand(C){const l=C.site.logo||{};return `<a class="brand" href="#inicio">${l.imageUrl?`<img src="${E(l.imageUrl)}" alt="${E(C.site.name)}">`:`<span class="brandText"><b>CATARINA<br>QUEIROZ</b><span>CLÍNICA ESTÉTICA</span></span>`}</a>`}
function head(C){const nav=[{label:'Início',href:'#inicio'},{label:'Procedimentos',href:'#procedimentos'},{label:'Método',href:'#metodo'},{label:'Sobre',href:'#sobre'},{label:'FAQ',href:'#faq'},{label:'Localização',href:'#localizacao'}];return `<header class="nav"><div class="container">${brand(C)}<nav class="links" id="links">${nav.map(n=>`<a href="${n.href}">${n.label}</a>`).join('')}</nav><a class="navCta" href="${wa(C)}">Agendar avaliação</a><button class="menu" id="menu"><span></span><span></span><span></span></button></div></header>`}
function ticker(C){const p=(C.sections.procedures.items||[]).map(x=>x.title);const line=[...p,...p];return `<div class="ticker"><div class="tickerInner">${line.map(x=>`<span>${E(x)}</span>`).join('')}</div></div>`}
function hero(C){const h=C.sections.hero;return `<section class="section hero dark" id="inicio"><div class="container heroGrid reveal"><div><div class="eyebrow">${E(h.kicker)}</div><h1 class="title">${E(h.title)}</h1><p class="lead">${E(h.subtitle)}</p><div class="actions"><a class="btn btnPrimary" href="${wa(C)}"><img src="${W}" alt="">${E(h.primaryButton)}</a><a class="btn btnOutline" href="#procedimentos">${E(h.secondaryButton)}</a></div><p class="lead" style="font-size:15px">${E(h.note)}</p></div><div class="photoMock">${h.image?.url?`<img src="${E(h.image.url)}" alt="">`:`<div class="mockText"><b>FOTO PRINCIPAL</b><span>coloque uma foto real da clínica</span></div>`}</div></div></section>`}
function complaints(C){const s=C.sections.complaints;return `<section class="section" id="queixas"><div class="container center reveal"><div class="eyebrow">${E(s.kicker)}</div><h2 class="title">A beleza que você quer valorizar tem um caminho certo.</h2><p class="lead">${E(s.subtitle)}</p><div class="cards3">${s.items.slice(0,6).map(x=>`<article class="card"><div class="iconBox">${ico(x.icon)}</div><h3>${E(x.title)}</h3><p>${E(x.text)}</p></article>`).join('')}</div></div></section>`}
function procedures(C){const s=C.sections.procedures;return `<section class="section dark" id="procedimentos"><div class="container procedureHead reveal"><div class="eyebrow">${E(s.kicker)}</div><h2 class="title">Procedimentos disponíveis após avaliação.</h2><p class="lead">${E(s.subtitle)}</p></div><div class="carouselWrap reveal"><div class="carousel" id="procedureCarousel">${s.items.map(x=>`<article class="procedureCard"><div class="procMedia">${x.imageUrl?`<img src="${E(x.imageUrl)}" alt="">`:`<strong>${E(x.title)}</strong>`}</div><div class="procContent"><span class="pill">FACIAL</span><h3>${E(x.title)}</h3><p>${E(x.description)}</p><div class="tags"><span>${E(x.icon)}</span></div><a class="btn btnPrimary" href="${wa(C,'Tenho interesse em '+x.title)}"><img src="${W}" alt="">Tenho interesse</a></div></article>`).join('')}</div><div class="container carouselBtns"><button class="circleBtn" data-car="-1">${ico('arrow-left')}</button><button class="circleBtn" data-car="1">${ico('arrow-right')}</button><div class="progress"><div class="bar"></div></div><b>Setas • arraste • swipe</b></div></div></section>`}
function method(C){const s=C.sections.method;return `<section class="section" id="metodo"><div class="container center reveal"><div class="eyebrow">Método Catarina Queiroz</div><h2 class="title">Um processo mais elegante que uma lista de procedimentos.</h2><p class="lead">${E(s.subtitle)}</p><div class="cards4">${s.steps.map(x=>`<article class="card"><div class="iconBox">${ico(x.icon)}</div><h3>${E(x.title)}</h3><p>${E(x.text)}</p></article>`).join('')}</div></div></section>`}
function featured(C){const f=C.sections.results?.items||[{title:'Endolaser',text:'Para quem busca melhora de contorno corporal, flacidez e gordura localizada.'},{title:'Drenagem HD',text:'Para reduzir inchaço e retenção de líquidos.'},{title:'Botox',text:'Para suavizar linhas mantendo naturalidade.'}];return `<section class="section compact"><div class="container center reveal"><div class="eyebrow">Protocolos em destaque</div><h2 class="title">Tratamentos que geram desejo na primeira visita.</h2><p class="lead">Uma vitrine curta para direcionar pacientes que já chegam com uma queixa mais definida.</p><div class="cards3">${f.slice(0,3).map(x=>`<article class="card"><span class="pill" style="color:#7a4e48;background:#f3e8df">${E(x.title)}</span><h3>${E(x.title)}</h3><p>${E(x.text)}</p><a class="btn btnPrimary" style="margin-top:28px" href="${wa(C,'Tenho interesse em '+x.title)}">Tenho interesse ${ico('arrow-right')}</a></article>`).join('')}</div></div></section>`}
function about(C){const s=C.sections.about;return `<section class="section" id="sobre"><div class="container split reveal"><div class="aboutPhoto">${s.image?.url?`<img src="${E(s.image.url)}" alt="">`:`<div class="mockText"><b>FOTO SOBRE</b><span>coloque uma foto real na clínica</span></div>`}</div><div class="aboutText"><div class="eyebrow">${E(s.kicker)}</div><h2 class="title">Catarina Queiroz</h2><p class="lead">${E(s.text)}</p><ul class="checkList">${(s.bullets||[]).map(b=>`<li>${E(b)}</li>`).join('')}</ul><a class="btn btnPrimary" href="${wa(C)}"><img src="${W}" alt="">Falar pelo WhatsApp</a></div></div></section>`}
function authority(C){const s=C.sections.authority;return `<section class="section"><div class="container center reveal"><div class="eyebrow">Confiança</div><h2 class="title">Mais segurança antes de decidir.</h2><p class="lead">Clareza na indicação, localização acessível e atendimento organizado para tornar a decisão mais segura.</p><div class="cards3">${s.items.map(x=>`<article class="card"><div class="iconBox">${ico(x.icon)}</div><h3>${E(x.title)}</h3><p>${E(x.text)}</p></article>`).join('')}</div></div></section>`}
function testimonials(C){const s=C.sections.testimonials;return `<section class="section" id="depoimentos"><div class="container center reveal"><div class="eyebrow">${E(s.kicker)}</div><h2 class="title">${E(s.title)}</h2><p class="lead">${E(s.subtitle)}</p><div class="carousel" style="padding-inline:0;margin-top:44px">${s.items.filter(x=>x.visible!==false).map(x=>`<article class="card" style="flex:0 0 350px;text-align:left"><div style="color:var(--gold)">★★★★★</div><p>“${E(x.text)}”</p><h3>${E(x.name)}</h3><p>${E(x.role||'')}</p></article>`).join('')}</div></div></section>`}
function faq(C){const s=C.sections.faq;return `<section class="section" id="faq"><div class="container center reveal"><div class="eyebrow">${E(s.kicker)}</div><h2 class="title">${E(s.title)}</h2><p class="lead">Respostas objetivas para reduzir atrito e facilitar o primeiro contato pelo WhatsApp.</p><div class="faqList">${s.items.map((x,i)=>`<article class="faqItem ${i==0?'open':''}"><button class="faqQ"><span>${E(x.question)}</span><span>+</span></button><div class="faqA">${E(x.answer)}</div></article>`).join('')}</div></div></section>`}
function location(C){const c=C.site.contact;const m=c.mapsEmbedUrl||`https://www.google.com/maps?q=${encodeURIComponent(c.mapsQuery||c.address)}&output=embed`;return `<section class="section dark" id="localizacao"><div class="container center reveal"><div class="eyebrow">Localização</div><h2 class="title">Atendimento em Boa Viagem, Recife.</h2><div class="locationGrid" style="margin-top:48px;text-align:left"><div class="infoBox"><h3>${E(C.site.businessName)}</h3><p><b>Endereço</b><br>${E(c.address)}</p><p><b>WhatsApp</b><br>${E(c.phoneDisplay)}</p><div class="actions"><a class="btn btnPrimary" href="${wa(C)}">Agendar</a><a class="btn btnOutline" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(c.mapsQuery||c.address)}">Traçar rota</a></div></div><div class="map"><iframe src="${m}" loading="lazy"></iframe></div></div></div></section>`}
function final(C){return `<section class="section compact dark"><div class="container center reveal"><h2 class="title">O próximo passo não é escolher um procedimento. É entender o que faz sentido para você.</h2><p class="lead">Fale com a clínica, explique sua principal queixa e receba orientação para agendar uma avaliação estética personalizada.</p><a class="btn btnPrimary" href="${wa(C)}" style="margin-top:30px">Agendar avaliação estética</a></div></section><footer class="footer"><div class="container footerGrid"><div>${brand(C)}<p>Estética facial e corporal em Boa Viagem, Recife.</p></div><div><b>Procedimentos</b><a>Limpeza de Pele</a><a>Drenagem HD</a><a>Endolaser</a><a>Botox</a></div><div><b>Navegação</b><a href="#inicio">Início</a><a href="#procedimentos">Procedimentos</a><a href="#metodo">Método</a><a href="#sobre">Sobre</a></div><div><b>Contato</b><p>WhatsApp: ${E(C.site.contact.phoneDisplay)}</p><p>${E(C.site.contact.address)}</p></div></div></footer><a class="whatsappFloat" href="${wa(C)}"><img src="${W}" alt="WhatsApp"></a>`}
function render(C){document.title=C.site.seo?.title||C.site.businessName;app.innerHTML=head(C)+ticker(C)+hero(C)+complaints(C)+procedures(C)+method(C)+featured(C)+about(C)+authority(C)+testimonials(C)+faq(C)+location(C)+final(C);window.lucide?.createIcons();bind()}
function bind(){document.querySelector('#menu')?.addEventListener('click',()=>document.querySelector('#links')?.classList.toggle('open'));document.querySelectorAll('.faqQ').forEach(b=>b.onclick=()=>b.closest('.faqItem').classList.toggle('open'));document.querySelectorAll('[data-car]').forEach(b=>b.onclick=()=>document.querySelector('#procedureCarousel')?.scrollBy({left:Number(b.dataset.car)*410,behavior:'smooth'}));const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.15});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));}
load().then(render).catch(e=>app.innerHTML=`<main class="section"><div class="container"><h1>Erro</h1><p>${E(e.message)}</p></div></main>`);
